- title: Articulate your Requirements
  icon: basic-elaboration-smartphone-heart
  content: When designing a product, we always think of how the user is going to experience it.
- title: Screening Applicants
  icon: basic-elaboration-message-happy
  content: No matter what you're stuck with, our support team will respond in the most adequate manner.
- title: Ranking the Candidates
  icon: basic-lightbulb
  content: Your fantasy is the limit here. Using our elements you can make anything come true.
- title: Managing Performance
  icon: basic-lock
  content: We don't take cyber security lightly, that's why our team put a lot of effort into securing this app.
- title: Swift performance
  icon: basic-bolt
  content: Powered by Materialize, this theme doesn't require page reloads, providing a seamless user experience.
- title: Beautifully designed
  icon: software-eyedropper
  content: Hand crafted with material design principles, with a focus on readability and white spaces.